### ISSUE TITLE
File location

### ISSUE THREAD

**Issue by sonu-kumar1** [jose-pleonasm/py-logging#1]
hello can you help me to know the log file location

**Comment by jose-pleonasm** [comment]
Hello, so you have to create some file handler first, like a FileHandler, and set it to an instance of Logger. And in this file handler you can specify the location of log file.

**Comment by sonu-kumar1** [comment]
how can we save logfile date wise.

**Comment by codey-singh** [comment]
Can we change the log file name on the fly @jose-pleonasm ?

**Comment by jose-pleonasm** [comment]
No, but you can create own file handler (which can inherit from the available and have only one new method, setFilename for example).

**Comment by codey-singh** [comment]
Yeah sure that makes sense. Thanks a lot
