### ISSUE TITLE
Can't find how to change the asctime to local date time rather than default ISO

### ISSUE THREAD

**Issue by Akhileshkumarr** [jose-pleonasm/py-logging#6]
I want to display asctime according to my current locale. Is there some mechanism to do so?
Thanks :)

**Comment by jose-pleonasm** [comment]
You can set up time format in your [Formatter](https://github.com/jose-pleonasm/py-logging/blob/master/API.md#Formatter). Format is similar as in [strftime](http://pubs.opengroup.org/onlinepubs/007908799/xsh/strftime.html) function in C. So for example '%c'.

**Comment by Akhileshkumarr** [comment]
Thanks Jose for quick reply, 
but can we convert the date time to any specific time zone (say IST) was my question?

**Comment by Akhileshkumarr** [comment]
Makes sense Jose, Thanks a lot :+1:
